ARG NODE_IMAGE=node:22.14.0-bullseye-slim
FROM ${NODE_IMAGE}
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
RUN npm install -g nodemon
COPY . .
RUN chmod 777 /usr/src/app/node_modules
ENV WATCHPACK_POLLING=true
EXPOSE 3000
CMD ["npm", "start"]
