version: '3'
services:
  api:
    build: ./api
    command: npm start
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - HOST=0.0.0.0
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE: ${VITE_API_BASE:-'http://localhost:3001'}
    ports:
      - '5173:80'
    environment:
      - VITE_API_BASE=${VITE_API_BASE}
    depends_on:
      - api
  api_db:
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db

volumes:
  mongodb_api:
