version: '3'
services:
  api:
    container_name: api_dev
    build:
      context: ./api
      dockerfile: Dockerfile.dev
      args:
        NODE_IMAGE: node:22.14.0-bullseye-slim
    command: npm run dev
    ports:
      # bind dev API to different host port to avoid colliding with prod
      - '3002:3001'
    environment:
      - PORT=3001
      - HOST=0.0.0.0
      - MONGO_URL=mongodb://api_db:27017/api
    volumes:
      - ./api/src:/usr/src/app/src
    depends_on:
      - api_db

  frontend:
    container_name: frontend_dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        NODE_IMAGE: node:22.14.0-bullseye-slim
    command: npm start
    ports:
      # bind dev frontend to a different host port for clarity
      - '3003:3000'
    environment:
      - VITE_API_BASE=${VITE_API_BASE:-http://localhost:3001}
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - api

  api_db:
    container_name: api_db_dev
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db

volumes:
  mongodb_api:
