version: '3'
services:
  nginx:
    container_name: nginx_prod
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
    depends_on:
      - api
      - frontend
    networks:
      - app-network
    restart: unless-stopped

  api:
    container_name: api_prod
    build:
      context: ./api
      args:
        NODE_IMAGE: node:22.14.0-alpine3.18
    command: npm start
    expose:
      - '3001'
    environment:
      - PORT=3001
      - HOST=0.0.0.0
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    container_name: frontend_prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        NODE_IMAGE: node:22.14.0-bullseye-slim
        VITE_API_BASE: '/api'
    command: serve -s build -l 3000
    expose:
      - '3000'
    environment:
      - VITE_API_BASE=/api
    depends_on:
      - api
    networks:
      - app-network
    restart: unless-stopped

  api_db:
    container_name: api_db_prod
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongodb_api:

networks:
  app-network:
    driver: bridge
