version: '3'
services:
  nginx:
    container_name: nginx_dev
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '8080:80'
    depends_on:
      - api
      - frontend
    networks:
      - app-network-dev
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx

  api:
    container_name: api_dev
    build:
      context: ./api
      dockerfile: Dockerfile.dev
      args:
        NODE_IMAGE: node:22.14.0-bullseye-slim
    command: npm run dev
    expose:
      - '3001'
    environment:
      - PORT=3001
      - HOST=0.0.0.0
      - MONGO_URL=mongodb://api_db:27017/api
    volumes:
      - ./api/src:/usr/src/app/src
    depends_on:
      - api_db
    networks:
      - app-network-dev

  frontend:
    container_name: frontend_dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        NODE_IMAGE: node:22.14.0-bullseye-slim
    command: npm start
    expose:
      - '3000'
    environment:
      - VITE_API_BASE=/api
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - api
    networks:
      - app-network-dev

  api_db:
    container_name: api_db_dev
    image: mongo:latest
    volumes:
      - mongodb_api_dev:/data/db
    networks:
      - app-network-dev

volumes:
  mongodb_api_dev:
  nginx_logs:

networks:
  app-network-dev:
    driver: bridge
